# ============================================================
# eureka-server.yml — Configuration d'eureka-server
# Dépôt : business-platform-config (GitHub)
#
# Ce fichier est distribué par le config-server à eureka-server
# au démarrage. Il complète application.yml.
# ============================================================

server:
  port: 8761

spring:
  application:
    name: eureka-server

# ── Paramètres Eureka Server ─────────────────────────────────
eureka:
  instance:
    hostname: eureka-server
  client:
    # Eureka ne s'enregistre pas chez lui-même
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Désactiver en développement — activer en production
    enable-self-preservation: false
    # Délai avant d'expulser un service non joignable (ms)
    eviction-interval-timer-in-ms: 5000
    # Pas d'attente au démarrage si le registre est vide
    wait-time-in-ms-when-sync-empty: 0

# ── Actuator ─────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info